# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-13 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrackModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_title', models.CharField(max_length=20)),
                ('track_genre', models.CharField(max_length=20)),
                ('track_rating', models.SmallIntegerField(blank=True, choices=[(0, 'Unrated'), (1, '1 star'), (2, '2 stars'), (3, '3 stars'), (4, '4 stars'), (5, '5 stars')], default=0)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='trackmodel',
            unique_together=set([('track_title', 'track_genre', 'track_rating')]),
        ),
    ]
