# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-14 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20160513_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackmodel',
            name='track_rating',
            field=models.CharField(blank=True, choices=[('0', 'Unrated'), ('1', '1 star'), ('2', '2 stars'), ('3', '3 stars'), ('4', '4 stars'), ('5', '5 stars')], default=0, max_length=8),
        ),
        migrations.AlterUniqueTogether(
            name='trackmodel',
            unique_together=set([('track_title', 'track_genre')]),
        ),
    ]
