# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-15 11:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20160514_2302'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenreModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='trackmodel',
            name='track_genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.GenreModel'),
        ),
    ]
