# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-15 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20160515_1100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genremodel',
            old_name='genre',
            new_name='genre_name',
        ),
        migrations.AlterField(
            model_name='trackmodel',
            name='track_genre',
            field=models.CharField(max_length=20),
        ),
    ]
