# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-15 12:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20160515_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackmodel',
            name='track_genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.GenreModel'),
        ),
    ]
